### ISSUE TITLE
Malformed xml: <debug> closing tag is </dispelga>

### ISSUE THREAD

**Issue by zombie343** [ThornyFFXI/Shorthand#3]
See: https://github.com/ThornyFFXI/Shorthand/blob/f6996b2bc2e2202c687b9150e7634b26fb36ab38/fileio.cpp#L44

The closing tag for <debug> is currently </dispelga>, which must be a typo or copy/paste error.

**Comment by ThornyFFXI** [comment]
Fixed in 1.15.
