### ISSUE TITLE
Can't cast offensive spells on charmed players or defensive spells on friendly NPCs

### ISSUE THREAD

**Issue by ShiyoKozuki** [ThornyFFXI/Shorthand#4]
Can't use // commands to cast offensive spells (i.e. sleep) on charmed players or defensive spells (i.e. cure) on friendly npcs (i.e. Faluuya in royal painter escort)

Using the in game magic menu works, but not // commands

**Comment by ThornyFFXI** [comment]
1.18 should fix it, but I don't have access to that specific BC or time to do extensive testing atm so I will leave issue open until confirmed.

**Comment by ShiyoKozuki** [comment]
can it be built in an earlier version of ashita? i can test it if it is
interface 4.15

**Comment by ThornyFFXI** [comment]
https://github.com/ThornyFFXI/Shorthand/releases/tag/1.19b

**Comment by ShiyoKozuki** [comment]
Works for charmed players, but not NPCs like Faluuya

If I type //cure while targetting a NPC like Faluuya it used to do nothing.
Now it'll cast on myself and not the target (Faluuya)

![image](https://github.com/ThornyFFXI/Shorthand/assets/58101246/4e8fea6a-8f4b-494d-975d-74ab8c20b0b7)
when I cast on her successfully it's through the in game magic menu

**Comment by ThornyFFXI** [comment]
I verified it works correctly on a couple of npcs on retail(demolition duty puppet and rank 1 periqia escort).  I am out of town until Sunday, but will check to see what is different about that NPC as soon as I am able to flag the quest(Mon or tues, iirc).

**Comment by ThornyFFXI** [comment]
On retail, shorthand is correctly recognizing her as a friendly target and allowing spells such as haste, protect, cure.  However, the server does block those casts(regardless of shorthand) until you approach her and she begins moving.  It seems this is likely an issue with your private server, unless it's the same behavior[preventing spells until she begins moving].
