### ISSUE TITLE
Target assumption not working

### ISSUE THREAD

**Issue by war3zlod3r** [ThornyFFXI/Shorthand#5]
On BLM //spell commands not working unless performed as //sleep <t> or //blizzard <t> not sure what the cause could be.

**Comment by ThornyFFXI** [comment]
Your report is unclear.  Could you provide an example of a command that does not work, and a command that does work?

**Comment by war3zlod3r** [comment]
sorry I didn't realize that my original post had the tags stripped out Ex: //sleep does nothing "//sleep `<t>"` does ass expected and casts sleep on the currently targeted monster

**Comment by ThornyFFXI** [comment]
Which server and which monster are you experiencing this on?  I tested those commands specifically on retail upon seeing your report, and they both correctly assume a target.

**Comment by war3zlod3r** [comment]
Horizon I first noticed it in Beauc on crabs at J-8

**Comment by ThornyFFXI** [comment]
And you are on the latest version of Shorthand, 1.21?

**Comment by war3zlod3r** [comment]
yes I updated when I noticed the issue, just tested again on a goblin outside Jueno no sleeps

**Comment by ThornyFFXI** [comment]
It seems likely that Horizon is not correctly setting monsters' allegiance or targetflags, since this is not an issue on retail.  I do not want to make shorthand worse to address their mistakes, so I will contact them about it.

**Comment by war3zlod3r** [comment]
roger thanks for the update if there's anything else I can do to test or assist in collecting data please let me know!

**Comment by ThornyFFXI** [comment]
Ah, upon further review it seems that this is just the horizon specific feature that prevents shorthand selecting monsters as a target.  Unfortunately, if you want to use the horizon-compliant version you will be unable to target monsters using anything besides an explicit `<parameter>`.  The other version works perfectly fine on horizon, but they have deemed it unacceptable because of people using it for claims.

**Comment by war3zlod3r** [comment]
Understood thank you for your time and explanation on the matter!
