### ISSUE TITLE
Feature Request: Option for automatic spell upscaling

### ISSUE THREAD

**Issue by dewiniaid** [ThornyFFXI/Shorthand#6]
My old 2007-era Windower alias setup worked as follows:

`//fire` casts the highest fire spell known at my level (at the time, this was aliased by running a script e.g. blm60.txt)
`//fire1` explicitly casts Fire.

I've been trying to find an elegant way to replace this and this seems like the most ideal way to do it.

Since it changes the default behavior, I imagine it should be a configuration option that is off by default.  My preference would be for it to be strictly based off of highest known -- i.e. if Fire III is in cooldown, it should still be chosen over a not-in-cooldown Fire II.  But other people may prefer it the other direction.  (Maybe it can be configured per spell?)

**Comment by ThornyFFXI** [comment]
Stop posting this everywhere.  I already linked you a solution to it the first time you asked about your old macro system in the ashita discord (the spellselect addon), and you continue to mention it in numerous places, many of which are not related.  This is not at all within shorthand's scope, and will not even be considered.

If there is a reason the addon you were already given is not sufficient, I am willing to listen in the appropriate channel (the ashita discord), when I am answering requests there.
